### ISSUE TITLE
Cant Start (Lato Origins (latoorigins) 1.19.2-1.1.0)

### ISSUE THREAD

**Issue by ZeroTronix** [DawngunnerYT/COBBLEMON-DAWN#1]
I just downloaded the modpack and get this error i cant even find the lato mod in the mod files.

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mod: 
	Drippy Loading Screen (drippyloadingscreen), Version: 3.0.9
		Mixin class: de.keksuccino.drippyloadingscreen.mixin.mixins.forge.client.MixinForgeLoadingOverlay
		Target: net.minecraftforge.client.loading.ForgeLoadingOverlay
		at TRANSFORMER/forge@47.3.7/net.minecraftforge.client.loading.ForgeLoadingOverlay.handler$kna000$drippyloadingscreen$cancelForgeCustomLoadingOverlayRenderingDrippy(ForgeLoadingOverlay.java:1027)
Stacktrace:
	at net.minecraftforge.logging.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:63) ~[forge-1.20.1-47.3.7-universal.jar%231603!/:?] {re:mixin,re:classloading}
-- NO MOD INFO AVAILABLE --
Details:
	Mod File: NO FILE INFO
	Failure message: Some of your mods are incompatible with the game or each other!
		A potential solution has been determined, this may resolve your problem:
		   - Replace mod Lato Origins (latoorigins) 1.19.2-1.1.0 with any version that is compatible with:
		     - minecraft 1.20.1
		More details:
		   - mod Lato Origins (latoorigins) 1.19.2-1.1.0 requires any 1.19.x version of mod Minecraft (minecraft), but only the wrong version is present: 1.20.1!
	Mod Version: NO MOD INFO AVAILABLE
	Mod Issue URL: NOT PROVIDED
	Exception message: MISSING EXCEPTION MESSAGE
Stacktrace:

**Comment by DawngunnerYT** [comment]
I will have a look at this shortly, can you provide me the log as well

**Comment by ZeroTronix** [comment]
https://mclo.gs/RHlt32V

**Comment by DawngunnerYT** [comment]
i'm going to keep looking into this however this is necessary to run the modpack on forge place entire file unziped in your named instanced folder ill also post this for others since forge seams to not be installing it for some. https://www.dropbox.com/scl/fo/wl818wnwffac1ll4i8w6g/AKEyS9x4fMnb_-p_VS5U_p4?rlkey=1z03r3wvgji3udhx8nrxynzp0&st=p8kdxhlm&dl=0

**Comment by ZeroTronix** [comment]
but why does it try to load this one mod xD and where is it

**Comment by ZeroTronix** [comment]
Ok idk why BUT i installed the modpack in an different launcher and The Lato mod is not the lato mod ... it shows this mod https://www.curseforge.com/minecraft/mc-mods/only-the-golem-origin/files/all?page=1&pageSize=20
I disabled the Golem.jar and now the modpack works

**Comment by DawngunnerYT** [comment]
hmm weird, thank you for finding it, i just wonder why it happened. works on my pc XD

**Comment by DawngunnerYT** [comment]
I see, its a fabric mod now with that link instead of forge, but same name, so it doesn't update on my end but its messing with everyone else.

**Comment by ZeroTronix** [comment]
Ahh ok still weird, now my goal is to put this modpack on my server xD

**Comment by DawngunnerYT** [comment]
Thank you so much, this will help plenty of others, I hope u can get it to work on a server pls enjoy

**Comment by ZeroTronix** [comment]
Yeah no Problem ^^ keep it up
